proxies:
- {"name":"🇳🇬 NGA Haruka Cloud","server":"shcua.donghui.tech","port":14836,"tfo":true,"type":"ss","cipher":"aes-128-gcm","password":"YX1SieTpVpImmCeEQ8ceRkXk7vGtX/1BZo+giXudaK0=","udp":true}